Update patch set 1
Patch Set 1:

Noticed that deployment failed due to nexus being read only 

Deploying directory /w/workspace/federation-maven-dl-merge-boreas/m2repo to https://nexus.acumos.org/content/repositories/snapshots
Uploading org/acumos/federation/federation-parent/maven-metadata.xml
Uploading org/acumos/federation/federation-parent/maven-metadata.xml.sha1
Uploading org/acumos/federation/federation-parent/maven-metadata.xml.md5
Uploading org/acumos/federation/federation-parent/0/federation-parent-0.pom
Uploading org/acumos/federation/federation-parent/0/federation-parent-0.pom.sha1
ERROR: Repository is read only
Build step 'Execute shell' marked build as failure

Patch-set: 1